# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d97897cc4988e8b55d1325e85264db708518553490837a6db737378e0fdb70c16ad855a541a24977a72384bd829b55181e3173bd4609de11609f347b0af342

test:
  secret_key_base: 67e45b98cd0b0bd91201aee6d430b8a238587c44317ad6b7c9bd1f28aaeaf92ec0b11b0841f6896a480e4dad09315ca8650cf82ba78abf6acc5221db2d6388bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
